### ISSUE TITLE
Second Bottom Card (cv_bot2) is not progressing to next question when swiped

### ISSUE THREAD

**Issue by Yuncun** [kplutchak/Waffle_Android#8]
![image](https://cloud.githubusercontent.com/assets/1505391/6877405/4046e310-d4a7-11e4-8211-ecba7701c88a.png)

_Steps to reproduce_
    Pull commit 9d1181804ddd8dd50659ed953574c768841fffb5
    Let image load on first set of cards *
    Swipe a card
    Swipe bottom card on the new set of answers

*Possibly a result of poor network conditions

_Actual_
    Second set of cards does not load image
    Swiping second card will not submit answer or move the top card - question is only submitted when top card is swiped

_Log_
https://gist.github.com/Yuncun/15f78a4ac0a7a7debf0f
Receiving a non-crashing SocketTimeOutException in imageloader, leading me to suspect that it has to do with poor connectivity.

**Comment by kplutchak** [comment]
Yeah, I have been unable to reproduce this. I imagine that we just need to better handle cases where network connectivity is lost/poor.
